name: git flow

on:
  push:
    branches:
      - develop

jobs:
  merge-develop-to-master:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: 'develop'

    - name: Merge develop to master
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Bot"
        git checkout master
        git merge --no-ff develop -m "Merging develop to master"
        git push origin master
